### ISSUE TITLE
请问sentinel的关联限流功能测试了吗？

### ISSUE THREAD

**Issue by startjava** [Eric-Li323/cloud2021#1]
请问sentinel的关联限流功能测试了吗？

我这个功能一直没有测通。

**Comment by Eric-Li323** [comment]
sentinel关联限流应该是测通了，你可以在b站找个sentinel部分的视频一步一步再试一遍，sentinel涉及代码部分比较少，主要看配置。

**Comment by startjava** [comment]
没有找到相关内容，，好像都没有对关联进行测试，

**Comment by Eric-Li323** [comment]
https://www.bilibili.com/video/BV18E411x7eT?p=117
b站上有个关联测试
